plugins {
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(25)
    withSourcesJar()
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

repositories {
    mavenCentral()
    maven {
        name = 'Hypixel'
        url = 'https://repo.hypixel.net/repository/Hypixel/'
    }
    maven {
        name = 'TerraformersMC'
        url = 'https://maven.terraformersmc.com/releases/'
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
    implementation "net.hypixel:mod-api:${project.hypixel_mod_api_version}"
    compileOnly "com.terraformersmc:modmenu:${project.modmenu_version}"
}

processResources {
    inputs.property 'version', project.version
    filesMatching('fabric.mod.json') {
        expand version: project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release.set(25)
}

jar {
    from('LICENSE') {
        rename 'LICENSE', 'LICENSE_safari-king'
    }
    from('THIRD_PARTY_NOTICES.md')
}
